import React, { useState } from 'react'
import type { TripRecord } from '../services/api'

type SavedTripsViewProps = {
    trips: TripRecord[]
    onSelectTrip: (trip: TripRecord) => void
    onDeleteTrip: (id: string) => Promise<void>
    onExportTrip: (id: string) => void
    onCreateNew: () => void
}

export function SavedTripsView({
    trips,
    onSelectTrip,
    onDeleteTrip,
    onExportTrip,
    onCreateNew,
}: SavedTripsViewProps) {
    const [searchTerm, setSearchTerm] = useState('')
    const [statusFilter, setStatusFilter] = useState('all')

    const filtered = trips.filter(t => {
        const matchesSearch =
            t.origin.toLowerCase().includes(searchTerm.toLowerCase()) ||
            t.destination.toLowerCase().includes(searchTerm.toLowerCase()) ||
            (t.summary || '').toLowerCase().includes(searchTerm.toLowerCase())
        const matchesStatus = statusFilter === 'all' || t.status === statusFilter
        return matchesSearch && matchesStatus
    })

    return (
        <div className="saved-trips-view">
            <div className="section-heading-bar">
                <div>
                    <span className="section-kicker">Saved Journeys</span>
                    <h2>Trip Library ({trips.length})</h2>
                </div>
                <button className="button button-primary" onClick={onCreateNew}>
                    + Plan New Journey
                </button>
            </div>

            {/* Filter & Search Bar */}
            <div className="trips-filter-bar">
                <input
                    type="text"
                    placeholder="Search trips by destination or origin..."
                    value={searchTerm}
                    onChange={e => setSearchTerm(e.target.value)}
                    className="search-input"
                />
                <div className="status-filter-pills">
                    <button
                        className={`filter-pill ${statusFilter === 'all' ? 'active' : ''}`}
                        onClick={() => setStatusFilter('all')}
                    >
                        All ({trips.length})
                    </button>
                    <button
                        className={`filter-pill ${statusFilter === 'draft' ? 'active' : ''}`}
                        onClick={() => setStatusFilter('draft')}
                    >
                        Drafts
                    </button>
                    <button
                        className={`filter-pill ${statusFilter === 'confirmed' ? 'active' : ''}`}
                        onClick={() => setStatusFilter('confirmed')}
                    >
                        Confirmed
                    </button>
                </div>
            </div>

            {filtered.length === 0 ? (
                <div className="empty-trips-card">
                    <span className="empty-icon">🧳</span>
                    <h3>No trips found</h3>
                    <p>There are no trips matching your search filter.</p>
                </div>
            ) : (
                <div className="trips-grid-layout">
                    {filtered.map(trip => (
                        <div key={trip.id} className="saved-trip-box">
                            <div className="trip-box-top">
                                <span className="trip-route-badge">
                                    {trip.origin} &rarr; {trip.destination}
                                </span>
                                <span className={`status-pill status-${trip.status}`}>{trip.status}</span>
                            </div>

                            <h3 className="trip-box-destination">{trip.destination}</h3>
                            <p className="trip-dates-row">
                                📅 {trip.departure_date || 'Flexible'} {trip.return_date ? `to ${trip.return_date}` : ''}
                            </p>
                            <p className="trip-summary-snippet">
                                {trip.summary || 'Custom itinerary generated by TravelMind AI.'}
                            </p>

                            <div className="trip-box-meta">
                                <span>👥 {trip.travelers} Traveler(s)</span>
                                <strong>💰 {trip.budget ? `${trip.budget.toLocaleString()} ${trip.currency}` : 'Flexible'}</strong>
                            </div>

                            <div className="trip-box-actions">
                                <button className="button button-primary-sm" onClick={() => onSelectTrip(trip)}>
                                    View Full Plan
                                </button>
                                <button className="button button-outline-sm" onClick={() => onExportTrip(trip.id)} title="Export HTML">
                                    📥 Export
                                </button>
                                <button className="button button-danger-sm" onClick={() => onDeleteTrip(trip.id)} title="Delete trip">
                                    🗑️
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    )
}
